---
title: "<center> Aspects To Make NBA Players Successful <center>"
subtitle: "<center> STAT 5361 Project Proposal <center> "
author: "<center> Yuanwei Qiao, Zihan Qi <center>"
date: "<center> 10/13/2020 <center>"
output: pdf_document


---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Introduction

The [National Basketball Association](https://en.wikipedia.org/wiki/National_Basketball_Association)[1] (NBA) is an American men's professional basketball league. As composed of 30 teams (29 in the United States and 1 in Canada) and a history of over 70 years, it has become the most popular men's professional basketball league in the world. The NBA's regular season runs from October to April, with each team playing 82 games and the playoff tournament extends into June. As of 2020, NBA players are the world's best paid athletes by average annual salary per player. However, which aspects of data can help us value the NBA players? Which characteristics would make the NBA players successful? What combination of players would have a better chance to make a championship team? Those are the questions we want to evaluate for this project

# 2. Proposal

Players like Lebron James, James Harden, Kobe Bryant, Michael Jordan and etc... has been dominating the NBA league for over a decade. But how? In this project, we will be checking which characteristics (e.g age/height/weight) of the player affects their performances the most. Also, we will be exploring the specific box score statistics (e.g points/rebounds/assists per game) of all the players so that we can accurately evaluate each player.

# 3. Data Table

We downloaded the dataset file from Kaggle[2]. The dataset is consisted of all 2235 NBA players' data from 1996-2019. It contains 22 columns of data to record each player's information and their box score statistics. 





#### Citations:

URL: \
[1]:https://en.wikipedia.org/wiki/National_Basketball_Association \
[2]:https://www.kaggle.com/justinas/nba-players-data
