---
title: "Coordinate Descent on Penalized Least Squares"
author: "Yuanwei Qiao"
date: "10/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 3.5.4

# part 2
lambda_max = |z|


```{r code, results='hide'}

S <- function(z, lambda) {
      if (z>lambda){return(z-lambda)}
    if (abs(z)<=lambda){return(0)}
    if (z<(-lambda)){return(z+lambda)}
 }



pen_ls<- function( y, xmat,   lambda )

 {  
xmat=as.matrix(xmat) 
  tol = 1e-6
  iter = 100       
  w = solve(crossprod(xmat) + diag(lambda, ncol(xmat))) %*% crossprod(xmat,as.matrix(y))
 
 tol_curr = 1
  J = ncol(xmat)
  a = rep(0, J)
  c_ = rep(0, J)
  i = 1  
  while (tol < tol_curr && i < iter) {
    w_old = w 
    a = colSums(xmat^2)
    l = length(y)*lambda  
    c_ = sapply(1:J, function(j)  sum( xmat[,j] * (y - xmat[,-j] %*% w_old[-j]) ))
      for (j in 1:J) {
        w[j] = S(c_[j]/a[j], l/a[j])
      }    
    tol_curr = crossprod(w - w_old)  
    i = i + 1
  }
  return(w)
}



gen_data <- function(n, b, sigma = 1) {
  p <- length(b)
  x <- matrix(rnorm(n * p), n, p)
  colnames(x) <- paste0("x", 1:p)
  y <- c(x %*% b) + rnorm(n, sd = sigma)
  return(data.frame(y, x))
}

n <- 200
b <- c(1, -1, 2, rep(0, 7))
set.seed(920)
dat <- gen_data(n, b)

y=dat[,1]
xmat=dat[,-1]

pen_ls(y, xmat,  lambda=0.1)



```
